In [1]:
import pandas as pd
import glob
import os

In [286]:
def data_table(path = '..\data\cleaned'):
    
    
    '''
    This function receives a path for the data.
    It asks the initial and final dates wich are used to filter the original dataframe.
    Then it aks the hour for the funding fees, the percentages for the target price and the liquidation price and
    the minutes to analyse.
    With this data whe start a counter that is summed every time the liquidation price is not reached and
    the target price is reached.
    Prints the results
    
    Input:
    path - str; the path to the original data 
    
    
    Output:
    
    
    '''
    
    
    #Uses glob to get the list of files
    path = path
    files = glob.glob(path + "/*.csv")
    
    print("Select one of the data:")
    for i in files:
        print(i)
        
    #fet the file path
    file_path = input("File path")
    
    df = pd.read_csv(file_path, index_col="date")
    df.drop("Unnamed: 0",axis=1, inplace=True)
    df.index = pd.to_datetime(df.index)
    
    
    print()
    print("Select a date  between {} and {}".format(df.index.min(), df.index.max()))
    print()
    
    
    #get the inputs
    init_date = input("Begin date (format : year-month-day hour:min:sec). Ex: '2020-02-19 17:30:00':   ")
    final_date = input("Final date (format : year-month-day hour:min:sec). Ex: '2020-02-19 17:30:00':   ")
    print()
    hour = input("Select the funding hour (integer with two digits, ex : 16):   ")
    
    print()
    funding = float(input("Select the funding fee (as a decimal format, ex: 0.01):   "))
    print()
    target_price = float(input("Select the target price increase (as a decimal format, ex: 0.01):   "))
    print()
    liquidation_price = float(input("Select the liquidation price decrease (as a decimal format, ex: 0.01):   "))
    print()
    minutes = input("Select the minutes interval (integer with two digits, ex : 16):   ")
    print()
    filename = input("Name for the dataframe to save:  ")
    
    
    df_exact_hour = df_time_period.at_time(hour+":00")
    
    
    
    #Initialize the counter and the percentage
    counter = 0
    percentage = 0
    
    
    #Check if the max value from the fundingRate input is higher than the one from the dataframe 
    if funding > df_exact_hour['fundingRate'].values.max():
        
        #slice the dataframe with the hour and minutes provided
        df_sliced = df_time_period.between_time(start_time='{}:00'.format(hour), end_time='{}:{}'.format(hour,minutes))
        
        #gets the base price
        default_price = df_sliced['close'][0]
        
        # update the target and liquidation prices with the default price
        
        target_price= default_price * (1 +target_price)
        liquidation_price= default_price * (1 -liquidation_price)
        
        #iterates through the sliced dataframe and counts only if the liquidation price is higher
        # than the minimum of the day and the target price is below the high
        for i in df_sliced[['low', 'high']].iterrows():
            if liquidation_price >= i[1][0]:
                counter +=0
            elif target_price <= i[1][1]:
                counter +=1
        percentage = counter/len(df_sliced)
        
        #save the dataframe
        df_sliced.to_csv("..\saved_dataframes\{}.csv".format(filename))

    # If the funding is not higher stops
    else:
        
        print("The percentage selected for the funding fee is :{} , and for the select time period the"\
              "maximum fee is: {}. So funding fee is below the select percentage".format(fundingnding, df_exact_hour['fundingRate'].values.max()))
    

    
    print()


    print(("For the dates between {} and {}, considering the funding hour {} within {} minutes" \
    "period, the target price of: {} , the liquidation price of :{} the target price was hit on {}" \
    "of the total periods").format(init_date,final_date,hour,minutes,target_price,liquidation_price, percentage))

In [343]:
data_table()

Select one of the data:
..\data\cleaned\ADAUSDT.csv
..\data\cleaned\DOTUSDT.csv
..\data\cleaned\EOSUSDT.csv
..\data\cleaned\ETHUSDT.csv
..\data\cleaned\LINKUSDT.csv
..\data\cleaned\LTCUSDT.csv
..\data\cleaned\SXPUSDT.csv
..\data\cleaned\VETUSDT.csv
..\data\cleaned\XRPUSDT.csv
File path..\data\cleaned\ADAUSDT.csv

Select a date (minutes to be considered) between 2020-02-19 17:30:00 and 2021-02-19 12:00:00

Begin date (format : year-month-day hour:min:sec). Ex: '2020-02-19 17:30:00'2020-02-19 17:30:00
Final date (format : year-month-day hour:min:sec). Ex: '2020-02-19 17:30:00'2021-02-19 12:00:00

Select the funding hour (integer with two digits, ex : 16)21

Select the funding fee (as a decimal format, ex: 0.01)0.01

Select the target price increase (as a decimal format, ex: 0.01)0.01

Select the liquidation price decrease (as a decimal format, ex: 0.01)0.1

Select the minutes interval (integer with two digits, ex : 16)10

Name for the dataframe to save:  test

For the dates between 2020-02-19 17:30:00 and 2021-02-19 12:00:00, considering the funding hour 21 within 10 minutesperiod, the target price of: 0.061761500000000004 , the liquidation price of :0.055035 the target price was hit on 0.7287671232876712of the total periods

In [2]:

df = pd.read_csv("..\data\cleaned\ADAUSDT.csv", index_col="date")
df.drop("Unnamed: 0",axis=1, inplace=True)
df.index = pd.to_datetime(df.index)

In [3]:
df

,open,high,low,close,close_diff,fundingRate
date,,,,,,
2020-02-19 17:30:00,0.06259,0.06299,0.06259,0.06279,0.003195,0.0
2020-02-19 17:31:00,0.06287,0.06300,0.06251,0.06251,-0.005726,0.0
2020-02-19 17:32:00,0.06252,0.06271,0.06248,0.06271,0.003039,0.0
2020-02-19 17:33:00,0.06271,0.06276,0.06265,0.06272,0.000159,0.0
2020-02-19 17:34:00,0.06272,0.06278,0.06265,0.06277,0.000797,0.0
...,...,...,...,...,...,...
2021-02-19 11:56:00,0.94239,0.94469,0.94115,0.94134,-0.001114,0.0
2021-02-19 11:57:00,0.94134,0.94198,0.93867,0.94049,-0.000903,0.0
2021-02-19 11:58:00,0.94049,0.94220,0.94036,0.94220,0.001818,0.0
2021-02-19 11:59:00,0.94220,0.94271,0.94101,0.94244,0.000255,0.0
2021-02-19 12:00:00,0.94262,0.94470,0.94250,0.94382,0.001273,0.0

In [5]:
df = pd.read_csv("..\data\original\ADAUSDT.csv", )

In [6]:
df.head()

,Unnamed: 0,time,open,high,low,close,date,close_diff,fundingRate
0,0,1.582133e+12,0.06259,0.06299,0.06259,0.06279,2020-02-19 17:30:00,0.003195,NaN
1,1,1.582133e+12,0.06287,0.06300,0.06251,0.06251,2020-02-19 17:31:00,-0.005726,NaN
2,2,1.582134e+12,0.06252,0.06271,0.06248,0.06271,2020-02-19 17:32:00,0.003039,NaN
3,3,1.582134e+12,0.06271,0.06276,0.06265,0.06272,2020-02-19 17:33:00,0.000159,NaN
4,4,1.582134e+12,0.06272,0.06278,0.06265,0.06277,2020-02-19 17:34:00,0.000797,NaN